### ISSUE TITLE
non-existent command

### ISSUE THREAD

**Issue by Morenooo95** [smasty/g203-led#12]
Hi, I have a problem with your code,
nothings happens when I run the command: ` sudo ./g203-led.py solid 00FFFF`.
The system tell me that the `./g203-led.py` command not exist.
I'm new to GNU/Linux, so i don't know how to fixed this problem, 
I would like if you could help me.

Thank you and best ragards.
Moreno

**Comment by smasty** [comment]
you need to first install the script by following the install instructions in the readme.
