### ISSUE TITLE
Error: Device 046d:c084 not found.

### ISSUE THREAD

**Issue by robfrancken** [smasty/g203-led#8]
Not sure if I'm doing something wrong? I don't use Python scripts often.

```sh
python3.8 --version
Python 3.8.2
```

```sh
virtualenv ./env                                                                                                                                   
created virtual environment CPython3.8.2.final.0-64 in 174ms
  creator CPython3Posix(dest=/home/rob/Downloads/g203-led/env, clear=False, global=False)
  seeder FromAppData(download=False, distro=latest, idna=latest, pip=latest, contextlib2=latest, distlib=latest, setuptools=latest, six=latest, ipaddr=latest, appdirs=latest, requests=latest, pep517=latest, html5lib=latest, pkg_resources=latest, lockfile=latest, wheel=latest, retrying=latest, colorama=latest, packaging=latest, pytoml=latest, chardet=latest, progress=latest, certifi=latest, msgpack=latest, CacheControl=latest, pyparsing=latest, webencodings=latest, urllib3=latest, via=copy, app_data_dir=/home/rob/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
```
```sh
env/bin/pip install -r requirements.txt
Requirement already satisfied: pyusb==1.0.2 in ./env/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.0.2)
```

```
sudo ./g203-led.py solid 00FFFF
Error: Device 046d:c084 not found.
```

Would appreciate some help with this.

**Comment by sanderr** [comment]
I've just received my G203 and it seems its id differs from what is specified in this script. Could you run `lsusb | grep Logitech` and report the output? For me it returns `046d:c092` instead of the expected `046d:c084`. If it's the same for you you could probably get it working by replacing `g203_product_id = 0xc084` in `g203-led.py` with `g203_product_id = 0xc092`.
See libratbag/libratbag#1014.

**Comment by sanderr** [comment]
I just noticed you were the one that opened this issue on the libratbag project in the first place, so you probably managed to solve it. I'll leave my comment here for others to find.

**Comment by robfrancken** [comment]
Thanks, that does resolve the issue. I did end up using libratbag instead though :)

**Comment by EmmanuelMess** [comment]
I am having this issue too. My id is `046d:c092`.
