### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EmmanuelMess** [smasty/g203-led#9]
It seems that the script doesn't work with my Logitech G203. No errors displayed after I corrected the id.
The command is:
> sudo ./g203-led.py solid 000000

**Comment by smasty** [comment]
Do you have the Logitech G203 Prodigy, or G203 Lightspeed? Because this script was only tested on G203 Prodigy, might not work with the newer G203 Lightspeed.

**Comment by EmmanuelMess** [comment]
Lightsync, I think.

**Comment by smasty** [comment]
Yes, from the looks of it, G203 Lightsync has different RGB setup than the G203 Prodigy, so this script will not work as-is without modifications. I've updated the Readme to mention this.

**Comment by EmmanuelMess** [comment]
How did you find the codes for changing RGB for the prodigy?

**Comment by smasty** [comment]
I used USBPcap on Windows to capture the packets transmitted while changing RGB settings in the Logitech utility, then examined the captured packets in Wireshark, and lots of trial and error.
